steps:
  - id: build-push-deploy
    name: "us-central1-docker.pkg.dev/com-seankhliao/build/gotip"
    entrypoint: "sh"
    env:
      - "GGCR_EXPERIMENT_ESTARGZ=1"
    args:
      - "-c"
      - |
        set -ex \
        && go test -vet=all ./... && \
        skaffold run
